security:
    # Définition du hachage du mot de passe pour les utilisateurs authentifiés par mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # Configuration des fournisseurs de données pour l'authentification
    providers:
        client_provider:
            entity:
                class: App\Entity\Client
                property: mail
    # Configuration des pare-feux (firewalls)
    firewalls:
        dev:
            # Configuration pour le profil de développement et les ressources de développement
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # Configuration du pare-feu principal
            lazy: true
            provider: client_provider # Utilisation du fournisseur 'client_provider'
            form_login:
                login_path: app_login # URL du formulaire de connexion
                check_path: app_login # URL où soumettre le formulaire de connexion
                default_target_path: app_home # URL de redirection après une connexion réussie
            logout:
                path: app_logout # URL de déconnexion
                target: app_home # URL de redirection après une déconnexion réussie


            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

# Configuration de sécurité pour l'environnement de test
when@test:
    security:
        password_hashers:
            # Configuration spécifique pour le hachage du mot de passe dans les tests
            # Par défaut, le hachage du mot de passe est intensif en ressources et prend du temps.
            # Dans les tests, la sécurité maximale du hachage n'est pas cruciale, cela gaspille des ressources
            # et augmente le temps de test.
            #La configuration suivante réduit le facteur de travail aux valeurs les plus basses possibles.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur minimale pour bcrypt
                time_cost: 3 # Valeur minimale pour argon
                memory_cost: 10 # Valeur minimale pour argon
